name: Sudan Web Crawler CI

on:
  cron:
    - '0 0 * * *' # Run every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Sudan API Scraper
      run: |
        python guardian_scraper.py